modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="_Livid_"
logoFile="create_gravlax_logo.png"
description='''
A Create addon for culinary industry and food alchemy. Process sugar crops into crystals and molasses, recover sugar from molasses through the Steffen process, refine mineral salt, and concentrate potions into essences and seasonings. Built for future industrial extensions, including potential redstone production from processing byproducts.
'''

[[mixins]]
config="create_gravlax.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="[6.0.10,6.1.0)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="[19.21.0.247,)"
ordering="AFTER"
side="CLIENT"
